version: '3.6'
services:
  fileserver:
    restart: always
    build:
        context: ./fileserver
        dockerfile: Dockerfile
    volumes:
      - ./fileserver/static:/usr/src/app
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    restart: always
    depends_on:
      - "postgres"
      - "fileserver"
  frontend:
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - "graphql-engine"
volumes:
  db_data:

